title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
logo: "/assets/img/logo.png"

url: https://propeller-columbus.github.io/reference-docs/

aux_links:
  Proximity Website: https://columbuspropeller.com

