title: Propeller Reference Docs
description: Reference documentation for equipment, processes, and policy at Propeller makerspace.
theme: just-the-docs
logo: "/assets/img/logo.png"

baseurl: "/docs"

aux_links:
  Proximity Website: https://columbuspropeller.com

