title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
logo: "/assets/img/logo.png"

baseurl: "/reference-docs"
url: "https://propeller-columbus.github.io/"

aux_links:
  Proximity Website: https://columbuspropeller.com

