title: Propeller Reference Docs
description: Reference documentation for equipment, processes, and policy at Propeller makerspace.
theme: just-the-docs
logo: "/assets/img/logo.png"

url: https://propeller-columbus.github.io/

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      
aux_links:
  Proximity Website: https://columbuspropeller.com

